apiVersion: apps/v1
kind: Deployment
metadata:
  name: edureka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edureka
  template:
    metadata:
      labels:
        app: edureka
    spec:
      containers:
        - name: edureka
          image: smusuvathi/edureka:1.0
          ports:
            - containerPort: 3000
